### ISSUE TITLE
Use site title instead of tagline in headings

### ISSUE THREAD

**Issue by beaulebens** [Automattic/jetpack-onboarding#21]
Most steps use the tagline of the site, rather than the site title. The last step goes back to using the site title. We should consistently use the title/name.

**Comment by jessefriedman** [comment]
I’ve narrowed it down to being a problem in the `state`. I believe this because if I change the Title of the site in the `General -> Settings` area then refresh JPO it works correctly. It’s only after you set the Title and Description in the first step that things get gaffed.

**Comment by gravityrail** [comment]
This seems to have been fixed by https://github.com/Automattic/jetpack-onboarding/commit/b01bc52bb14762da28df764a7766c30d1a20989e
