### ISSUE TITLE
Jetpack settings link doesn't work

### ISSUE THREAD

**Issue by MichaelArestad** [Automattic/jetpack-onboarding#24]
Not that I can actually connect successfully on my test blog, but if I force the congratulations step (to check out the UX), I found the "settings page" link doesn't work. Also, there is some funky positioning. Is this step even accessible by a user? CC @ryelle @goldsounds

**Comment by ryelle** [comment]
That page shows up if the user has already connected their Jetpack. I just pushed an update to master that grabs the real link. Part of the funky positioning is probably that the button is being floated right with a [style applied to the component](https://github.com/Automattic/jetpack-onboarding/blob/master/client/components/steps/jetpack-jumpstart.jsx#L63).

**Comment by MichaelArestad** [comment]
Yeah. I tried getting to it after already connecting to JP and couldn't get it to show.
