### ISSUE TITLE
Missing step in final steps list

### ISSUE THREAD

**Issue by jessefriedman** [Automattic/jetpack-onboarding#30]
**What's wrong:**
We've added the business address step but at the end of the JPO flow it doesn't show in the list. 

**What I expected**
To see a check mark next to "Business Address Added" in this view 
![screen shot 2016-08-25 at 2 26 29 pm](https://cloud.githubusercontent.com/assets/1749986/17981062/0ccf6d98-6ad0-11e6-8eee-1adda74bbf3e.png)

**Comment by johnHackworth** [comment]
fixed in https://github.com/Automattic/jetpack-onboarding/pull/29
