### ISSUE TITLE
Failing to connect Jetpack 

### ISSUE THREAD

**Issue by jessefriedman** [Automattic/jetpack-onboarding#32]
When I click "Connect to WordPress.com" button I get the following error: 

`Error enabling Jetpack: Server error`

![screen shot 2016-08-29 at 12 23 45 pm](https://cloud.githubusercontent.com/assets/1749986/18058751/cbb81d2a-6de3-11e6-961c-e822bf1c9070.png)

I have tried reseting the plugin, deactivating it and nothing seems to work. 

cc/ @johnHackworth and @gravityrail (in case you have some insight into this)

**Comment by roccotripaldi** [comment]
I'm just starting to use this plugin today, and I also get that error. I'll do some digging.

**Comment by roccotripaldi** [comment]
@jessefriedman - are you by chance on a multi-site?  I can only reproduce the error in a multi-site environment, and I think I know how to fix it. But i'd like to confirm wether or not this is limited to multi-site.

**Comment by jessefriedman** [comment]
I was not on a multi-site but on my sandbox. I can make you an admin if
that helps

**Comment by tyxla** [comment]
I confirm that this issue occurs only with the new Jetpack React.
