### ISSUE TITLE
Business Address step doesn't show if you haven't connected Jetpack

### ISSUE THREAD

**Issue by jessefriedman** [Automattic/jetpack-onboarding#37]
I understand that Jetpack being connected is required for the user to get the benefits of the widget but we should still show the test, and let the widget show up later if the user connects Jetpack later. 

This step: 
<img width="1046" alt="screen shot 2016-10-20 at 3 39 34 pm" src="https://cloud.githubusercontent.com/assets/1749986/19575218/6e7c3620-96db-11e6-872b-0d88e7f8209a.png">

Should show no matter what their Jetpack connection status is as long as they have indicated that they are in fact a building business website

**Comment by tyxla** [comment]
This was done on purpose in this commit: https://github.com/Automattic/jetpack-onboarding/commit/fe913f8a6ac2fe6c78c6b18999570d12d697264e.
