### ISSUE TITLE
WooCommerce Installation step has a checkbox 

### ISSUE THREAD

**Issue by jessefriedman** [Automattic/jetpack-onboarding#39]
We should remove the checkbox seen here: 
<img width="1045" alt="screen shot 2016-10-20 at 3 42 28 pm" src="https://cloud.githubusercontent.com/assets/1749986/19575291/d48a4e20-96db-11e6-9adf-05481a4fd5d3.png">
and change the "Next Step" cta to say "Install WooCommerce".  Pressing that button should perform the action of installing and activating Woo

**Comment by jessefriedman** [comment]
Let's use this design: https://cloudup.com/ceEHVzBSAGb

But keep the current "not now" button that exists and ignore the "skip" button in the mockup

**Comment by ryelle** [comment]
Looks like this was fixed in https://github.com/Automattic/jetpack-onboarding/commit/0d13637dd5a0ff0b947a7df4346a861ea0a6520c, so I'm closing this issue.
