### ISSUE TITLE
If I don't change my Title I get an error when I move forward through JPO

### ISSUE THREAD

**Issue by jessefriedman** [Automattic/jetpack-onboarding#41]
If I have previously changed the title of my site, or I'm not ready to choose one now and press the "Next Step" button seen below I get an error.
<img width="1128" alt="screen shot 2016-10-20 at 3 38 32 pm" src="https://cloud.githubusercontent.com/assets/1749986/19575402/63a30a52-96dc-11e6-90e2-483e71302d04.png">

<img width="1041" alt="screen shot 2016-10-20 at 3 38 37 pm" src="https://cloud.githubusercontent.com/assets/1749986/19575420/78e5a41a-96dc-11e6-8380-35be625f7588.png">

**Comment by ryelle** [comment]
I can't seem to replicate this - I thought I saw a comment about it being related to the apostrophe, but even with that I don't get it. @jessefriedman are you still seeing this?

**Comment by jessefriedman** [comment]
Good call, I think Rocco fixed this previously
