### ISSUE TITLE
Incorrect base URL

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack-onboarding#50]
@ashleighaxios pinged me today about broken images when testing Jetpack Onboarding. After looking into it, it seems that the issue is how we set the base URL.

https://github.com/Automattic/jetpack-onboarding/blob/master/jetpack-onboarding.php#L10

I think we should set it to something like:

`plugins_url( '', __FILE__ );`

**Comment by gravityrail** [comment]
Fixed in https://github.com/Automattic/jetpack-onboarding/commit/021c291c842a1c4a2fd1a39ea84a595ec84ae892
